import { FC, ReactNode } from 'react'
import { prisma } from '@g/prisma/prisma-client'
import { Metadata } from 'next'

import '@/core/shared/styles/index.scss'
import { ProvidersThreeComponent } from '@/app/elements/layout/elements/provider-tree'
import { primaryFont } from '@/core/shared/fonts'
import { NavBarStoreProvider } from '@/core/shared/store/navbar/navbar.provider'
import { LayoutWidget } from '@/core/widgets/layout'

interface RootLayoutProps {
  children: ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const Layout: FC<RootLayoutProps> = async ({ children }) => {
  const navbar = await prisma.navbar.findMany({
    include: {
      link: {
        select: {
          slug: true,
        },
      },
    },
  })

  const openHours = await prisma.freeHours.findMany()

  return (
    <html className={primaryFont.className}>
      <body>
        <NavBarStoreProvider
          initialData={{
            navbar: navbar,
            openHours: openHours,
          }}
        >
          <ProvidersThreeComponent>
            <LayoutWidget>{children}</LayoutWidget>
          </ProvidersThreeComponent>
        </NavBarStoreProvider>
      </body>
    </html>
  )
}
export default Layout
