import type {Metadata} from "next";
import '@/core/shared/styles/index.scss'
import {primaryFont} from "@/core/shared/fonts";
import { NextIntlClientProvider } from 'next-intl'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <NextIntlClientProvider>

    <html lang="en" suppressHydrationWarning>
      <body
        className={primaryFont.className}
      >
        {children}
      </body>
    </html>
    </NextIntlClientProvider>
  );
}

